inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
