inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/Output:
  Exclude:
    - db/seeds.rb

FactoryBot/ExcessiveCreateList:
  Exclude:
    - spec/models/doctor_spec.rb

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'
