x-backend-app: &backend-app
  build:
    context: .
    dockerfile: Dockerfile.dev
  environment:
    DB_USERNAME: postgres
    DB_PASSWORD: postgres
    DB_PORT: 5432
    DB_HOST: postgres
    EDITOR: 'nano'
  stdin_open: true
  tty: true

services:
  backend:
    <<: *backend-app
    entrypoint: ./docker-entrypoint-dev.sh
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/rails:rw
      - /rails/tmp/cache/bootsnap
      - /rails/node_modules
    ports:
      - "3000:3000/tcp"

    depends_on:
      - postgres

  postgres:
    image: postgres:11.16-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    volumes:
      - /var/lib/postgresql/data

